service: flask-app

provider:
  name: aws
  runtime: python3.9

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
